version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python src/api/main.py
    # if FastAPI, use: command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
